### ISSUE TITLE
Vignettes in Readme

### ISSUE THREAD

**Issue by vnminin** [fintzij/BDAepimodel#1]
Add vignette names to the Readme, so the user knows how to open them when they download the package.

**Comment by fintzij** [comment]
Oops, I had actually made those edits but forgot to re-knit the readme. Thanks.

**Comment by Spatial-R** [comment]
hello, i can't install this package in my compute (ubuntu 14.04)

**Comment by fintzij** [comment]
Hello,

Try installing with the following command. I made some changes to the code
and am in the process of rewriting the vignettes. The new vignettes should be up within the week.

Cheers,
Jon

install_github("fintzij/BDAepimodel",build_vignettes=FALSE)

**Comment by Spatial-R** [comment]
Actuualy, i still can't install the package using the following codes:
install_github("fintzij/BDAepimodel",build_vignettes=FALSE)

the errors are:

collect2: error: ld terminated with signal 11 , core dumped
buildEigenAnalytic.o:(.data.rel.local._ZZN4arma16arma_stream_err1IcEERSoPSoE11stream_err1[_ZZN4arma16arma_stream_err1IcEERSoPSoE11stream_err1]+0x0): `std::ostream& arma::arma_stream_err1<char>(std::ostream*)::stream_err1'

**Comment by fintzij** [comment]
Hi,

Apologies, those .o files should not have been in the src/ directory. You should be able to install without difficulty now. Also, the vignettes are up to date, so it will work with build_vignettes=TRUE in the command.

Cheers,
Jon
