### ISSUE TITLE
pomp vignettes don't build

### ISSUE THREAD

**Issue by bnguyenvanyen** [fintzij/BDAepimodel#2]
Hi,
```R
install_github("fintzij/BDAepimodel", build_vignettes=TRUE)
```
fails on the pomp vignettes with 
```
   Error: processing vignette 'SEIR_pomp_simulation.Rmd' failed with diagnostics:
   in 'pmcmc': in 'pfilter': in 'rprocess': variable 'S' not found among the state variables.
```

Do you have a fix, and otherwise is there a way to avoid building those vignettes specifically to still get the other ones ?

Thank you

**Comment by fintzij** [comment]
Hi, 

Apologies, not quite sure why the pomp vignettes no longer build properly. I have placed the pomp vignettes in the [inst/pomp_vignettes](https://github.com/fintzij/BDAepimodel/tree/master/inst/pomp_vignettes) directory, so they are accessible but no longer build upon installation. The package can now be installed using the install_github command as before.

Cheers,
Jon
