### ISSUE TITLE
installing BDAepimodel

### ISSUE THREAD

**Issue by Yalthoba1407** [fintzij/BDAepimodel#3]
I tried to install BDAepimodel, and encountered this issue
Error: Failed to install 'BDAepimodel' from GitHub:
System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> --- finished re-building 'popsize_misspecification.Rmd'
E>
E> --- re-building 'prior_effect.Rmd' using rmarkdown
E> Warning: The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is "Additional simulations included Fintzi, Wakefield, and Minin (2016)", and the latter is "Effect of prior specification on posterior inference". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check.
E> --- finished re-building 'prior_effect.Rmd'
E>
E> Error: Duplicate vignette titles.
E> Ensure that the %\VignetteIndexEntry lines in the vignette sources
E> correspond to the vignette titles.
E> Execution halted

**Comment by fintzij** [comment]
I've updated the yaml headers in the vignettes. Can you confirm whether this has resolved the issue for you?

**Comment by Yalthoba1407** [comment]
thank you for your reply
